import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useAuth } from '@nhost/react-auth';
import { Flex } from '@chakra-ui/react';
import { Layout } from '../../components/Layout';

function SiteIndex() {
  const router = useRouter();
  const { signedIn } = useAuth();

  useEffect(() => {
    if (signedIn) {
      router.push('/home');
    } else {
      router.push('/');
    }
  }, []); // eslint-disable-line

  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Flex direction="column" width="100%" padding="20px">
          Redirecting...
        </Flex>
      </Layout>
    </>
  );
}

export default SiteIndex;
