import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useAuth } from '@/lib/hooks';
import { Layout, LoadingScreen } from '@/components';

function SiteIndex() {
  const router = useRouter();
  const { isAuthenticated } = useAuth();

  useEffect(() => {
    if (isAuthenticated) {
      router.push('/home');
    } else {
      router.push('/');
    }
  }, []); // eslint-disable-line

  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <LoadingScreen label="Redirecting to Dashboard..." />
      </Layout>
    </>
  );
}

export default SiteIndex;
