import Head from 'next/head';
import { gql, useQuery, useMutation } from '@apollo/client';
import { WithPrivateRoute } from '../components/WithPrivateRoute';
import { Layout } from '../components/Layout';
import { SiteItem } from '../components/SiteItem';
import { CreateSiteModal } from '../components/CreateSiteModal';
import { auth } from '../lib/nhost';
import { Entity } from '../lib/enums';
import type { AggregateData, SiteType } from '../lib/types';

type SitesAggregateData = AggregateData<SiteType, Entity.Sites>;

export const SITES_AGGREGATE = gql`
  query SITES_AGGREGATE($userId: uuid!) {
    sites_aggregate(
      limit: 10,
      offset: 0,
      where: {user: {id: {_eq: $userId}}}
    ) {
      nodes {
        description
        id
        name
        slug
        status
        user {
          id
        }
      }
    }
  }
`;

export const INSERT_SITE_ONE = gql`
mutation INSERT_SITE_ONE($object: sites_insert_input!) {
  insert_sites_one(object: $object) {
    created_at
    id
    description
    name
    slug
  }
}

`;

function Home() {
  const {
    loading: queryLoading,
    data: queryData,
    error: queryError,
  } = useQuery<SitesAggregateData>(
    SITES_AGGREGATE,
    {
      variables: {
        userId: auth.getClaim('x-hasura-user-id'),
      },
      context: {
        headers: {
          'x-hasura-role': 'me',
        },
      },
    },
  );

  const [addSite, { data, mutationLoading, mutationError }] = useMutation(INSERT_SITE_ONE);
  console.log('### mutationError: ', mutationError);
  console.log('### data: ', data);

  const sites = queryData?.sites_aggregate?.nodes?.filter((s) => !!s);

  if (queryLoading && !queryData) {
    return <div>Loading...</div>;
  }

  if (queryError || !sites) {
    console.error(queryError); // eslint-disable-line
    return <div>Error getting sites data</div>;
  }

  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <CreateSiteModal onSubmit={addSite} />

        {sites.map((site) => <SiteItem key={site.id} name={site.name} />)}
      </Layout>
    </>
  );
}

export default WithPrivateRoute(Home);
