import Head from 'next/head';
import { gql, useQuery } from '@apollo/client';
import { Box, HStack } from '@chakra-ui/react';
import { auth } from '../lib/nhost';
import { Entity } from '../lib/enums';
import type { AggregateData, SiteType } from '../lib/types';

type SitesAggregateData = AggregateData<SiteType, Entity.Sites>;

export const SITES_AGGREGATE = gql`
  query SITES_AGGREGATE($userId: uuid!) {
    sites_aggregate(
      limit: 10,
      offset: 0,
      where: {user: {id: {_eq: $userId}}}
    ) {
      nodes {
        description
        id
        name
        slug
        status
        user {
          id
        }
      }
    }
  }
`;

export default function Home() {
  const { loading, data, error } = useQuery<SitesAggregateData>(
    SITES_AGGREGATE,
    {
      variables: {
        userId: auth.getClaim('x-hasura-user-id'),
      },
      context: {
        headers: {
          'x-hasura-role': 'me',
        },
      },
    },
  );

  const sites = data?.sites_aggregate?.nodes;

  if (loading && !data) {
    return <div>Loading...</div>;
  }

  if (error || !sites) {
    console.error(error); // eslint-disable-line
    return <div>Error getting user data</div>;
  }

  console.log('### sites: ', sites);

  return (
    <div>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Next.js
        </h1>
      </main>

      {sites.map((site) => (
        <HStack key={site.id}>
          <Box>{site.name}</Box>
        </HStack>
      ))}
    </div>
  );
}
